// Countries the user can pick from the header's country selector. `name`
// and `demonym` are both used server-side (app/api/news/route.js) to bias
// the NewsAPI search toward that country (e.g. "India OR Indian"), since
// NewsAPI's free plan doesn't support real per-country top-headlines.

export const COUNTRIES = [
  { code: "pk", name: "Pakistan", demonym: "Pakistani" },
  { code: "global", name: "🌍 Global (BBC, CNN, Reuters...)", demonym: null },
  { code: "af", name: "Afghanistan", demonym: "Afghan" },
  { code: "ar", name: "Argentina", demonym: "Argentine" },
  { code: "au", name: "Australia", demonym: "Australian" },
  { code: "at", name: "Austria", demonym: "Austrian" },
  { code: "bd", name: "Bangladesh", demonym: "Bangladeshi" },
  { code: "be", name: "Belgium", demonym: "Belgian" },
  { code: "bh", name: "Bahrain", demonym: "Bahraini" },
  { code: "br", name: "Brazil", demonym: "Brazilian" },
  { code: "ca", name: "Canada", demonym: "Canadian" },
  { code: "cl", name: "Chile", demonym: "Chilean" },
  { code: "cn", name: "China", demonym: "Chinese" },
  { code: "co", name: "Colombia", demonym: "Colombian" },
  { code: "dk", name: "Denmark", demonym: "Danish" },
  { code: "eg", name: "Egypt", demonym: "Egyptian" },
  { code: "fi", name: "Finland", demonym: "Finnish" },
  { code: "fr", name: "France", demonym: "French" },
  { code: "de", name: "Germany", demonym: "German" },
  { code: "gh", name: "Ghana", demonym: "Ghanaian" },
  { code: "gr", name: "Greece", demonym: "Greek" },
  { code: "in", name: "India", demonym: "Indian" },
  { code: "id", name: "Indonesia", demonym: "Indonesian" },
  { code: "ir", name: "Iran", demonym: "Iranian" },
  { code: "iq", name: "Iraq", demonym: "Iraqi" },
  { code: "ie", name: "Ireland", demonym: "Irish" },
  { code: "il", name: "Israel", demonym: "Israeli" },
  { code: "it", name: "Italy", demonym: "Italian" },
  { code: "jp", name: "Japan", demonym: "Japanese" },
  { code: "ke", name: "Kenya", demonym: "Kenyan" },
  { code: "kw", name: "Kuwait", demonym: "Kuwaiti" },
  { code: "my", name: "Malaysia", demonym: "Malaysian" },
  { code: "mx", name: "Mexico", demonym: "Mexican" },
  { code: "np", name: "Nepal", demonym: "Nepali" },
  { code: "nl", name: "Netherlands", demonym: "Dutch" },
  { code: "nz", name: "New Zealand", demonym: "New Zealand" },
  { code: "ng", name: "Nigeria", demonym: "Nigerian" },
  { code: "no", name: "Norway", demonym: "Norwegian" },
  { code: "om", name: "Oman", demonym: "Omani" },
  { code: "ph", name: "Philippines", demonym: "Filipino" },
  { code: "pl", name: "Poland", demonym: "Polish" },
  { code: "pt", name: "Portugal", demonym: "Portuguese" },
  { code: "qa", name: "Qatar", demonym: "Qatari" },
  { code: "ru", name: "Russia", demonym: "Russian" },
  { code: "sa", name: "Saudi Arabia", demonym: "Saudi" },
  { code: "sg", name: "Singapore", demonym: "Singaporean" },
  { code: "za", name: "South Africa", demonym: "South African" },
  { code: "kr", name: "South Korea", demonym: "Korean" },
  { code: "es", name: "Spain", demonym: "Spanish" },
  { code: "lk", name: "Sri Lanka", demonym: "Sri Lankan" },
  { code: "se", name: "Sweden", demonym: "Swedish" },
  { code: "ch", name: "Switzerland", demonym: "Swiss" },
  { code: "th", name: "Thailand", demonym: "Thai" },
  { code: "tr", name: "Turkey", demonym: "Turkish" },
  { code: "ua", name: "Ukraine", demonym: "Ukrainian" },
  { code: "ae", name: "United Arab Emirates", demonym: "Emirati" },
  { code: "gb", name: "United Kingdom", demonym: "British" },
  { code: "us", name: "United States", demonym: "American" },
  { code: "vn", name: "Vietnam", demonym: "Vietnamese" },
];

export function countryMeta(code) {
  return COUNTRIES.find((c) => c.code === code) || null;
}
